version: '3.4'

services:
  server:
    container_name: server
    restart: always
    env_file: .env
    build:
      context: .
      dockerfile: ./Dockerfile
    command: "java -Xss100m -Xms512m -Xmx5g -server -jar /web/server/Order-shop-web.jar"
    volumes:
      - "${LOG_PATH}/server:/log"
  client:
    container_name: client
    restart: always
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./web/src/main/typescript/Dockerfile
    command: "npm run start"
    depends_on:
      - server
  proxy:
    image: nginx:latest
    container_name: proxy
    env_file: .env
    hostname: ${HOST}
    ports:
      - "${APP_PORT}:433"
    volumes:
      - "${PROXY_DIRECTORY}:/etc/nginx/conf.d"
      - "${LOG_PATH}/proxy:/var/log/nginx"
    depends_on:
      - client